# Generated by Django 4.2.7 on 2023-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplyee',
            new_name='Employee',
        ),
    ]
